"""remove exam student_count

Revision ID: 11d636654806
Revises: 9d2b7c4a1f21
Create Date: 2026-06-28 20:25:18.481764

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "11d636654806"
down_revision: str | None = "9d2b7c4a1f21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exam", "student_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exam",
        sa.Column("student_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
