"""add_exam_updated_at

Revision ID: 529137af94fc
Revises: 773b0b5bb86e
Create Date: 2026-06-21 20:30:10.510099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "529137af94fc"
down_revision: Union[str, None] = "773b0b5bb86e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exam", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exam", "updated_at")
    # ### end Alembic commands ###
