"""initial

Revision ID: 773b0b5bb86e
Revises:
Create Date: 2026-06-21 18:33:56.348211

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "773b0b5bb86e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member",
        sa.Column("member_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("profile_key", sa.String(), nullable=True),
        sa.Column("affiliation", sa.String(), nullable=True),
        sa.Column(
            "affiliation_role",
            sa.Enum("PROFESSOR", "TEACHER", "TUTOR", "TA", name="affiliationrole"),
            nullable=False,
        ),
        sa.Column("role", sa.Enum("ADMIN", "NORMAL", name="role"), nullable=False),
        sa.PrimaryKeyConstraint("member_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "exam",
        sa.Column("exam_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("member_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("problem_sheet_file_key", sa.String(), nullable=True),
        sa.Column("model_answer_file_key", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "SETUP", "OCR", "GRADING", "DONE", name="examstatus"),
            nullable=False,
        ),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.member_id"],
        ),
        sa.PrimaryKeyConstraint("exam_id"),
    )
    op.create_table(
        "problem",
        sa.Column("problem_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("exam_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "MULTIPLE_CHOICE",
                "SHORT_ANSWER",
                "DESCRIPTIVE",
                "CODING",
                name="problemtype",
            ),
            nullable=False,
        ),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("region", sa.JSON(), nullable=True),
        sa.Column(
            "language",
            sa.Enum("CPP", "JAVA", "PYTHON", "C", name="programminglanguage"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exam.exam_id"],
        ),
        sa.PrimaryKeyConstraint("problem_id"),
    )
    op.create_table(
        "student",
        sa.Column("student_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("exam_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("student_no", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exam.exam_id"],
        ),
        sa.PrimaryKeyConstraint("student_id"),
        sa.UniqueConstraint("exam_id", "student_no"),
    )
    op.create_table(
        "answer_sheet",
        sa.Column(
            "answer_sheet_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("exam_id", sa.BigInteger(), nullable=False),
        sa.Column("student_id", sa.BigInteger(), nullable=True),
        sa.Column("file_key", sa.String(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("MATCHED", "UNMATCHED", name="sheetstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exam.exam_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.student_id"],
        ),
        sa.PrimaryKeyConstraint("answer_sheet_id"),
    )
    op.create_index(
        "uq_answer_sheet_exam_student",
        "answer_sheet",
        ["exam_id", "student_id"],
        unique=True,
        postgresql_where=sa.text("student_id IS NOT NULL"),
    )
    op.create_table(
        "grade",
        sa.Column("grade_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("problem_id", sa.BigInteger(), nullable=False),
        sa.Column("student_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("CONFIRMED", "SUGGESTED", name="gradestatus"),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum("AUTO", "LLM", "HUMAN", name="grademethod"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.student_id"],
        ),
        sa.PrimaryKeyConstraint("grade_id"),
        sa.UniqueConstraint("problem_id", "student_id"),
    )
    op.create_table(
        "job",
        sa.Column("job_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("exam_id", sa.BigInteger(), nullable=False),
        sa.Column("problem_id", sa.BigInteger(), nullable=True),
        sa.Column("requested_by_member_id", sa.BigInteger(), nullable=False),
        sa.Column("retry_of_job_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "MODEL_ANSWER_OCR",
                "RUBRIC_SUGGEST",
                "ANSWER_SHEET_RECOGNIZE",
                "REGION_TEMPLATE_APPLY",
                "ANSWER_OCR_RUN",
                "AUTO_GRADE",
                "LLM_GRADE",
                "EXPORT_CSV",
                name="jobtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "DONE", "FAILED", "CANCELED", name="jobstatus"
            ),
            nullable=False,
        ),
        sa.Column("input_json", sa.JSON(), nullable=True),
        sa.Column("progress_json", sa.JSON(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error_json", sa.JSON(), nullable=True),
        sa.Column("celery_task_id", sa.String(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exam.exam_id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_member_id"],
            ["member.member_id"],
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_job_id"],
            ["job.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "model_answer",
        sa.Column(
            "model_answer_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("problem_id", sa.BigInteger(), nullable=False),
        sa.Column("correct_choice", sa.Integer(), nullable=True),
        sa.Column("choice_count", sa.Integer(), nullable=True),
        sa.Column("accepted_answers", sa.JSON(), nullable=True),
        sa.Column("model_answer_text", sa.Text(), nullable=True),
        sa.Column("region", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
        ),
        sa.PrimaryKeyConstraint("model_answer_id"),
        sa.UniqueConstraint("problem_id"),
    )
    op.create_table(
        "rubric",
        sa.Column("rubric_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("problem_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("allocated_score", sa.Integer(), nullable=False),
        sa.Column(
            "source", sa.Enum("LLM", "HUMAN", name="rubricsource"), nullable=False
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
        ),
        sa.PrimaryKeyConstraint("rubric_id"),
    )
    op.create_table(
        "answer_region",
        sa.Column(
            "answer_region_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("answer_sheet_id", sa.BigInteger(), nullable=False),
        sa.Column("problem_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "shape", sa.Enum("RECT", "LASSO", name="regionshape"), nullable=False
        ),
        sa.Column("bbox_region", sa.JSON(), nullable=True),
        sa.Column("polygon_points", sa.JSON(), nullable=True),
        sa.Column(
            "layout_mode", sa.Enum("FIXED", "FREE", name="layoutmode"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["answer_sheet_id"],
            ["answer_sheet.answer_sheet_id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.problem_id"],
        ),
        sa.PrimaryKeyConstraint("answer_region_id"),
        sa.UniqueConstraint("answer_sheet_id", "problem_id"),
    )
    op.create_table(
        "ocr_result",
        sa.Column("ocr_result_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("answer_region_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("marked_choice", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.Enum("RAW", "REVIEWED", name="ocrstatus"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["answer_region_id"],
            ["answer_region.answer_region_id"],
        ),
        sa.PrimaryKeyConstraint("ocr_result_id"),
        sa.UniqueConstraint("answer_region_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ocr_result")
    op.drop_table("answer_region")
    op.drop_table("rubric")
    op.drop_table("model_answer")
    op.drop_table("job")
    op.drop_table("grade")
    op.drop_index(
        "uq_answer_sheet_exam_student",
        table_name="answer_sheet",
        postgresql_where=sa.text("student_id IS NOT NULL"),
    )
    op.drop_table("answer_sheet")
    op.drop_table("student")
    op.drop_table("problem")
    op.drop_table("exam")
    op.drop_table("member")
    # ### end Alembic commands ###
