"""add_student_regions_to_exam_remove_page_count_from_answer_sheet

Revision ID: a2e5b9c82335
Revises: e2c24a7f9577
Create Date: 2026-06-22 20:21:20.644929

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a2e5b9c82335"
down_revision: str | None = "e2c24a7f9577"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answer_sheet", "page_count")
    op.add_column("exam", sa.Column("student_name_region", sa.JSON(), nullable=True))
    op.add_column("exam", sa.Column("student_no_region", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exam", "student_no_region")
    op.drop_column("exam", "student_name_region")
    op.add_column(
        "answer_sheet",
        sa.Column("page_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
