"""remove_problem_name_make_label_nonnullable

Revision ID: e2c24a7f9577
Revises: 529137af94fc
Create Date: 2026-06-22 15:41:19.778905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2c24a7f9577'
down_revision: Union[str, None] = '529137af94fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('problem', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('problem', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
