from enum import Enum


class JobType(str, Enum):
    MODEL_ANSWER_OCR = "MODEL_ANSWER_OCR"
    RUBRIC_SUGGEST = "RUBRIC_SUGGEST"
    ANSWER_SHEET_RECOGNIZE = "ANSWER_SHEET_RECOGNIZE"
    REGION_TEMPLATE_APPLY = "REGION_TEMPLATE_APPLY"
    ANSWER_OCR_RUN = "ANSWER_OCR_RUN"
    AUTO_GRADE = "AUTO_GRADE"
    LLM_GRADE = "LLM_GRADE"
    EXPORT_CSV = "EXPORT_CSV"
